name: CI for Payment Service

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Kubernetes Config Repository
        uses: actions/checkout@v3
        with:
          repository: 'Deliveroo-System/ds-project-kubernetes'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: kubernetes
          

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -f Payment-Service/Dockerfile -t vidura12/deliveroo:payment-service-latest Payment-Service


      - name: Push Docker image to Docker Hub
        run: docker push vidura12/deliveroo:payment-service-latest
